import { ServiceDuties } from "@/types/serviceDuties";
import { FORM_NAME } from "./forms";
import { SERVICE } from "./master";


export const SERVICE_DUTIES: ServiceDuties = {
  [SERVICE.ANIMALS]: [
    FORM_NAME.ADD_ANIMAL,
    FORM_NAME.ADD_SPECIE,
    FORM_NAME.UPDATE_ANIMAL,
  ],
  [SERVICE.FOOD]: [
    FORM_NAME.ADD_FOOD_STOCK,
    FORM_NAME.UPDATE_FOOD_STOCK,
    FORM_NAME.ADD_FOOD_TYPE,
    FORM_NAME.UPDATE_FOOD_TYPE,
    FORM_NAME.ADD_STORAGE_UNIT,
    FORM_NAME.UPDATE_STORAGE_UNIT,
    FORM_NAME.ADD_STORAGE_UNIT_TYPE,
    FORM_NAME.UPDATE_STORAGE_UNIT_TYPE
  ],
  [SERVICE.STAFF]: [
    FORM_NAME.ADD_STAFF,
    FORM_NAME.UPDATE_STAFF,
    FORM_NAME.ADD_DEPARTMENT,
    FORM_NAME.UPDATE_DEPARTMENT
  ],
  [SERVICE.BREEDING]: [],
  [SERVICE.ENCLOSURES]: [
    FORM_NAME.ADD_ENCLOSURE,
    FORM_NAME.ADD_ENCLOSURE_TYPE,
    FORM_NAME.UPDATE_ENCLOSURE,
    FORM_NAME.UPDATE_ENCLOSURE_TYPE,
  ],
  [SERVICE.REPORTS]: []

}